import React from 'react'
import CardList from './CardList'
import img1 from '../../Assets/img-1.webp'
import './Mumbai.css'
const Mumbai = () => {
    var Cards =[{
        id: 1,
        img: img1,
        title : "lorem",
        room: 2,
        bed:2,
        bath: 1,
        area: "445sft",
        rent: "$4200",
      },
        {id: 2,
        img: img1,
        title: "lorem",
        room: 3,
        bed:3,
        bath: 2,
        area: "443sft",
        rent: "$4000",
      },
        {id: 3,
            img: img1,
        title: "lorem",
        room: 3,
        bed:2,
        bath: 1,
        area: "545sft",
        rent: "$4000",
      },
        {id: 4,
            img: img1,
        title: "lorem",
        room: 3,
        bed:2,
        bath: 1,
        area: "425sft",
        rent: "$4000",
      },
        {id: 5,
            img: img1,
        title: "lorem",
        room: 3,
        bed:2,
        bath: 1,
        area: "445sft",
        rent: "$4000",
      },
        {id: 6,
            img: img1,
        title: "lorem",
        room: 3,
        bed:2,
        bath: 1,
        area: "545sft",
        rent: "$4000",
      },
        {id: 7,
            img: img1,
        title: "lorem",
        room: 3,
        bed:2,
        bath: 1,
        area: "425sft",
        rent: "$4000",
      },
        {id: 8,
            img: img1,
        title: "lorem",
        room: 3,
        bed:2,
        bath: 1,
        area: "445sft",
        rent: "$4000",
      },
       { id: 9,
        img: img1,
        title: "lorem",
        room: 3,
        bed:2,
        bath: 1,
        area: "445sft",
        rent: "$4000",
      }]
  return (
    <CardList Cards={Cards}/>
  )
    }

export default Mumbai
